---
# Introduction to Machine Learning - Lab 2
---

Following are the steps to import a dataset (Iris.csv) and preparing the confusion matrix and classification report.

---
# Importing the dataset
---

In [100]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
bankdata = pd.read_csv("Iris.csv")

# Finding the Shape of the Dataset
---

In [101]:
bankdata.shape

(150, 6)

# Finding the Head of the Dataset
---

In [102]:
bankdata.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Dropping the Class Column
---

In [103]:
X=bankdata.drop('Species',axis=1)
Y=bankdata['Species']
print(X)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]


# Splitting the dataset into 80%/20% for Training/Test sections
---

In [104]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20)

# Training the Models
---

In [105]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='linear')
svclassifier.fit(X_train,Y_train)
y_pred=svclassifier.predict(X_test)

# Checking the test cases using the test data
---

### Printing the confusion matrix and classification report

In [106]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[ 8  0  0]
 [ 0 13  0]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00         9

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

