---
# Introduction to Machine Learning - Lab 2.3
---

Following are the steps to import a dataset (HR_comma_sep.csv) and preparing the confusion matrix and classification report.

**Note:**
- In the original 'HR_comma_sep_org.csv' dataset, we see a column headed as 'salary', the values of which, are discrete, i.e, 'High' , 'Medium' or 'Low'. But such string based data can neither be used in a machine learning model nor be dropped. So for the sake of computation, the values are converted into equivalent numerical values. '0' stands for 'low' , '1' coreresponds 'medium' and '2' corresponds 'high'.

- After making the above modification, the dataset is renamed as HR_comma_sep.csv' and used for the following notebook.

---
# Importing the dataset
---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
hrdata = pd.read_csv("HR_comma_sep.csv")

# Finding the Shape of the Dataset
---

In [2]:
hrdata.shape

(14999, 10)

# Finding the Head of the Dataset
---

In [3]:
hrdata.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0       0  
1       1  
2       1  
3       0  
4       0

# Dropping the Class Column
---

In [4]:
X=hrdata.drop('sales',axis=1)
Y=hrdata['sales']
print(X)

       satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272            

# Splitting the dataset into 80%/20% for Training/Test sections
---

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20)

# Training the Models
---

In [6]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='linear')
svclassifier.fit(X_train,Y_train)
y_pred=svclassifier.predict(X_test)

# Checking the test cases using the test data
---

### Printing the confusion matrix and classification report

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[  0   0   0   0   0   0   0 237   0   0]
 [  0   0   0   0   0   0   0 175   0   0]
 [  0   0   0   0   0   0   0 150   0   0]
 [  0   0   0   0   0   0   0 156   0   0]
 [  0   0   0   0   0   0   0 116   0   0]
 [  0   0   0   0   0   0   0 178   0   0]
 [  0   0   0   0   0   0   0 198   0   0]
 [  0   0   0   0   0   0   0 821   0   0]
 [  0   0   0   0   0   0   0 434   0   0]
 [  0   0   0   0   0   0   0 535   0   0]]
              precision    recall  f1-score   support

          IT       0.00      0.00      0.00       237
       RandD       0.00      0.00      0.00       175
  accounting       0.00      0.00      0.00       150
          hr       0.00      0.00      0.00       156
  management       0.00      0.00      0.00       116
   marketing       0.00      0.00      0.00       178
 product_mng       0.00      0.00      0.00       198
       sales       0.27      1.00      0.43       821
     support       0.00      0.00      0.00       434
   technical       0.00     

/home/sayak/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sayak/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sayak/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
